ЁЯОЙтЬи *ржкрж╛ржЦрж┐ЁЯе╣ <тБй, рж╕рзНржмрж╛ржЧрждржо ржкрж╛ржЦрж┐ ЁЯТЭтЬи
ЁЯОнDRAMA GROUP ЁЯОн!* тЬиЁЯОЙ

ЁЯШК ржПржЗ ржЧрзНрж░рзБржкрзЗ ржерж╛ржХрзЛ ржЖрж░ ржЦрзБрж╢рж┐ ржерж╛ржХрзЛЁЯе╣тЬи!
ЁЯСе *ржПржЦржи ржорзЛржЯ рж╕ржжрж╕рзНржп:* 
ЁЯУв *ржирж┐ржпрж╝ржо:* ржорж┐рж▓рзЗржорж┐рж╢рзЗ ржерж╛ржХржмрж╛ рж╕ржмрж╛ржЗржХрзЗ рж╕ржорзНржорж╛ржи ржХрж░ржмрж╛!
